list: $/vdomah/roles/models/role/columns.yaml
modelClass: Vdomah\Roles\Models\Role
title: Roles
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'vdomah/roles/roles/update/:id'
showTree: true